mash-up-kr/chinchin-android

- app/src/main/AndroidManifest.xml
- presenter/src/main/java/com/mashup/presenter/dev/BridgeActivity.kt
- presenter/src/main/java/com/mashup/presenter/receive_alarm/ReceiveAlarmActivity.kt
- presenter/src/main/java/com/mashup/presenter/receive_alarm/model/RequestAlarm.kt
- presenter/src/main/java/com/mashup/presenter/receive_alarm/model/RequestAlarmUiModel.kt
- presenter/src/main/java/com/mashup/presenter/ui/receive_alarm/ReceiveAlarmComponent.kt
- presenter/src/main/java/com/mashup/presenter/ui/theme/Color.kt
일단 UI만 러프하게 개발 했습니당
아이콘, 폰트 등은 아직 수정되지 않았어요
> #11 나에게 온 요청 리스트 UI 개발

- presenter/src/main/java/com/mashup/presenter/ui/receive_alarm/ReceiveAlarmComponent.kt
- presenter/src/main/java/com/mashup/presenter/ui/theme/Color.kt
> feat: #14 color 네이밍 통일

- presenter/src/main/java/com/mashup/presenter/main/MainActivity.kt
- presenter/src/main/java/com/mashup/presenter/ui/main/MainComponent.kt
- presenter/src/main/java/com/mashup/presenter/ui/main/MainNavScreen.kt
- presenter/src/main/java/com/mashup/presenter/ui/theme/Color.kt
- presenter/src/main/res/drawable/icon_home.xml
- presenter/src/main/res/drawable/icon_more.xml
- presenter/src/main/res/drawable/icon_search.xml
* 메인 네비게이션 바의 아이콘, 색상 등을 적용
* NavScreen의 리스트를 한 번에 가져오기 위해 enum class로 변경
* 아이콘의 ImageVector 생성 위치 변경
* 아이콘 추가
* 네비게이션 바 색상 변경
> #19 메인 네비게이션 바 디자인 적용

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/mashup/chinchin/application/App.kt
- build.gradle
- data/build.gradle
- data/src/main/java/com/mashup/data/dao/ChinChinDao.kt
- data/src/main/java/com/mashup/data/database/ChinChinDatabase.kt
- data/src/main/java/com/mashup/data/database/ChinChinTypeConverters.kt
- data/src/main/java/com/mashup/data/di/DBModule.kt
- data/src/main/java/com/mashup/data/di/RepositoryModule.kt
- data/src/main/java/com/mashup/data/dto/local/ChinChin.kt
- data/src/main/java/com/mashup/data/repository/ChinChinRepository.kt
- data/src/main/java/com/mashup/data/repository/impl/ChinChinRepositoryImpl.kt
- domain/build.gradle
- domain/src/main/java/com/mashup/domain/di/UseCaseModule.kt
- domain/src/main/java/com/mashup/domain/model/ChinChinModel.kt
- domain/src/main/java/com/mashup/domain/usecase/ChinChinUseCase.kt
- domain/src/main/java/com/mashup/domain/usecase/impl/ChinChinUseCaseImpl.kt
- presenter/build.gradle
- presenter/src/main/java/com/mashup/presenter/dev/BridgeActivity.kt
- presenter/src/main/java/com/mashup/presenter/main/MainActivity.kt
- presenter/src/main/java/com/mashup/presenter/room_test/RoomTestActivity.kt
- presenter/src/main/java/com/mashup/presenter/room_test/RoomTestViewModel.kt
1. #5 Room연동  작업 너무 많이 수정되어서 #29 로 merge하였습니다
변경사항
1. room 적용 
2. flow사용
3.  RoomTestActivity, ViewModel 생성하고 add, delete, update 테스트
> #29 room연동

- presenter/src/main/java/com/mashup/presenter/main/MainActivity.kt
- presenter/src/main/java/com/mashup/presenter/ui/main/home/HomeComponent.kt
- rebase 하다가 constraint 걸린 부분 코드 그대로 넣어서 제거함ㅎ
- Column으로 header, body 묶고, 가장 부모 Column에 padding horizontal 24dp 넣음
> refact: #18 constraint 걸려있던부분 제거

- app/src/main/AndroidManifest.xml
- presenter/src/main/java/com/mashup/presenter/common/ChinChinQuestionCardState.kt
- presenter/src/main/java/com/mashup/presenter/common/model/QuestionUiModel.kt
- presenter/src/main/java/com/mashup/presenter/dev/BridgeActivity.kt
- presenter/src/main/java/com/mashup/presenter/friend_detail/FriendDetailActivity.kt
- presenter/src/main/java/com/mashup/presenter/reply_preference/ReplyPreferenceActivity.kt
- presenter/src/main/java/com/mashup/presenter/reply_preference/model/ReplyPreferenceQuestionUiModel.kt
- presenter/src/main/java/com/mashup/presenter/ui/common/ChinChinComponent.kt
- presenter/src/main/java/com/mashup/presenter/ui/friend_detail/FriendDetailContentComponent.kt
- presenter/src/main/java/com/mashup/presenter/ui/friend_detail/FriendDetailNavGraph.kt
- presenter/src/main/java/com/mashup/presenter/ui/reply_preference/ReplyPreferenceComponent.kt
- presenter/src/main/res/drawable/icon_check.xml
요청 질문 답변 화면 UI를 개발
* 요청 질문 답변 화면 UI 개발
* QuestionCard를 친구 디테일 컴포넌트에서 공통 컴포넌트로 변경
* QuestionUiModel를 CommonModel로 이동
* QuestionCard의 색상 추가(타입으로 구분)
* 툴바에 확인 버튼 추가하면서 백버튼 관련 기본값 추가
* 코드의 변경사항이 너무 많아지는 것 같아서 카드의 입력 관련 부분은 따로 이슈 파서 작업하겠습니당..
> #38 요청 질문 답변 화면 UI

- presenter/build.gradle
- presenter/src/main/java/com/mashup/presenter/add_friend/AddFriendActivity.kt
- presenter/src/main/java/com/mashup/presenter/set_group/SetGroupActivity.kt
- presenter/src/main/java/com/mashup/presenter/ui/add_friend/AddFriendComponent.kt
- presenter/src/main/java/com/mashup/presenter/ui/common/ChinChinComponent.kt
- presenter/src/main/java/com/mashup/presenter/ui/set_group/SetGroupComponent.kt
- 그룹 지정하기 activity 연동
- 안드로이드 기본 달력 다이얼로그 연동(색 지정 아시는 분..ㅠㅠ 민트색이 별로 예쁘지 않네요)
- 데이터 모두 들어갔을 때 버튼 enable 설정
> feat: 40 친구 디테일 작성 페이지 UI 연동

- app/src/main/AndroidManifest.xml
- presenter/src/main/java/com/mashup/presenter/dev/BridgeActivity.kt
- presenter/src/main/java/com/mashup/presenter/dialog_test/DialogActivity.kt
- presenter/src/main/java/com/mashup/presenter/ui/dialog_tests/DialogComponent.kt
- presenter/src/main/res/drawable/ic_x.xml
질문 키워드 dialog 구현
1. test activity생성(삭제 예정)
2. dialog 구현 로직
- x버튼, 바깥 영역을 선택하면 dialog 삭제하고 이전 선택된 값 유지 
- 키워드 선택하기 버튼 클릭하면 라디오 버튼에 선택된 값으로 변경 함
3. todo
- 희진이가 구현한거랑 합칠 수 있도록 uiModel 연결 해야 됨
> feat: #42 질문 키워드 Dialog 구현

- presenter/src/main/java/com/mashup/chinchin/presenter/ui/common/ChinChinComponent.kt
chinchinButton의 크기를 조절했습니다
내부에 패딩이 잘못 설정되어있었네요 ㅎ;;
> #55 chinchinButton 크기 조절

- presenter/src/main/java/com/mashup/chinchin/presenter/common/ChinChinQuestionCardState.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/common/model/CategoryUiModel.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/common/model/KeywordQuestionUiModel.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/send_preference/SendPreferenceActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/common/ChinChinComponent.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/send_questions/SendPreferenceComponent.kt
자유질문 클릭시 질문추가 가능하도록
취향키워드 및 개인정보의 경우 클릭시 다이얼로그 연결
https://user-images.githubusercontent.com/37477660/182031219-4e535d78-f923-48b7-ab00-c58fd6775d67.mp4
> 취향질문지 보내기 다이얼로그와 연결

- presenter/src/main/java/com/mashup/chinchin/presenter/ui/common/NormalDialog.kt
타이틀만 있는 다이얼로그 추가했습니당
사용처에는 따로 적용은 안했어요!
> #61 타이틀만 있는 다이얼로그 추가

- presenter/src/main/java/com/mashup/chinchin/presenter/ui/add_friend/AddFriendComponent.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/common/ChinChinComponent.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/set_group/SetGroupComponent.kt
- 그룹 추가하기 다이얼로그
- 중앙정렬 수정
- 다이얼로그 크기 수정
- TextField 잘리는 문제 해결
- ChinChinGreyTextField로 빼놨음 -> 친구 추가하기 화면에서도 사용하도록 바꿔놓음
> 그룹 추가하기 다이얼로그 수정

- presenter/src/main/java/com/mashup/chinchin/presenter/set_group/SetGroupActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/set_group/SetGroupComponent.kt
라디오 버튼들을 스크롤 가능하게 변경
그룹 추가 버튼이 스크롤 범위 안에 포함되도록 변경
> feat: #81 radiobutton들이 스크롤 가능하게 변경

- presenter/src/main/java/com/mashup/chinchin/presenter/common/CardState.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/common/ChinChinAnswerCardState.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/common/ChinChinQuestionCardState.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/common/ChinChinComponent.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/reply_preference/ReplyPreferenceComponent.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/send_questions/SendPreferenceComponent.kt
> feat: #95 카드 상태 변경

- app/src/main/AndroidManifest.xml
- presenter/src/main/java/com/mashup/chinchin/presenter/add_friend/AddFriendActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/connect_friend/ConnectFriendActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/friend_detail/FriendDetailActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/group_detail/GroupDetailActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/main/MainActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/main/model/FriendUiModel.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/main/model/RecommendFriendUiModel.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/common/ChinChinComponent.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/connect_friend/ConnectFriendComponent.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/group_detail/GroupDetailComponent.kt
- 기존 친구 연결하기 화면
- 신규 친구 추가 화면
- 기존친구 search bar 양옆 정렬
- 연결하시겠습니까? 다이얼로그 네 클릭시 친구 상세 연결
> 기존친구 연결하기 페이지 

- presenter/src/main/java/com/mashup/chinchin/presenter/main/MainActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/main/MainNavGraph.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/main/home/HomeComponent.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/main/recommend_friends/RecommendFriendsComponent.kt
수정사항
* 추천 친구탭 로고 추가
* 추천 친구 프로필 이미지 나오도록 수정
* 친구 더보기 버튼 추가 (기능은 없음)
> #62 recommend friend UI 수정

- data/src/main/java/com/mashup/chinchin/data/datasource/remote/RemoteGroupDataSource.kt
- data/src/main/java/com/mashup/chinchin/data/di/RepositoryModule.kt
- data/src/main/java/com/mashup/chinchin/data/dto/remote/requestbody/CreateNewGroupRequestBody.kt
- data/src/main/java/com/mashup/chinchin/data/dto/remote/responsebody/CreateNewGroupResponseBody.kt
- data/src/main/java/com/mashup/chinchin/data/repository/GroupRepositoryImpl.kt
- data/src/main/java/com/mashup/chinchin/data/service/ChinChinService.kt
- domain/src/main/java/com/mashup/chinchin/domain/repository/GroupRepository.kt
- domain/src/main/java/com/mashup/chinchin/domain/usecase/CreateNewGroupUseCase.kt
- presenter/build.gradle
- presenter/src/main/java/com/mashup/chinchin/presenter/main/MainActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/main/home/HomeViewModel.kt
그룹 추가 api 연결 했습니당
* HiltViewModel을 주입받기 위해 디펜던시를 추가했는데, 이거 관련해서 조금 더 자세히 보고 수정될 가능성이 있습니다 (필요해서 일단 넣었음..)
> #100 그룹 추가 api 연결

- data/src/main/java/com/mashup/chinchin/data/di/NetworkModule.kt
- data/src/main/java/com/mashup/chinchin/data/network/TokenInterceptor.kt
> #109 토큰 인터셉터 추가

- presenter/src/main/java/com/mashup/chinchin/presenter/add_friend/AddFriendActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/connect_friend/ConnectFriendActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/friend_detail/FriendDetailActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/group_detail/GroupDetailActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/login/LoginActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/main/MainActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/receive_alarm/ReceiveAlarmActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/reply_preference/ReplyPreferenceActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/send_preference/SendPreferenceActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/send_preference/SendPreferenceCompleteActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/set_group/SetGroupActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/common/StatusBar.kt
파랑이 보기싫오서 statusbar 색 바꿨는데..고민이 이씁니다. 
composable은 앞에가 대문자잖아요?
근데 색을 변경하는거라 동사일텐데.. 이름을 뭐라고 지어야할지 고민이 되었습니다.
원래같으면 setStatusBarColor / initStatusBar이런식으로 했을텐데.. 추천받아요
SetStatusBarColor?..
> feat: #111 statusbar 색 변경

- data/src/main/java/com/mashup/chinchin/data/datasource/remote/RemoteAlarmDataSource.kt
- data/src/main/java/com/mashup/chinchin/data/di/RepositoryModule.kt
- data/src/main/java/com/mashup/chinchin/data/dto/remote/responsebody/IsAlarmResponseBody.kt
- data/src/main/java/com/mashup/chinchin/data/repository/AlarmRepositoryImpl.kt
- data/src/main/java/com/mashup/chinchin/data/service/ChinChinService.kt
- domain/src/main/java/com/mashup/chinchin/domain/repository/AlarmRepository.kt
- domain/src/main/java/com/mashup/chinchin/domain/usecase/IsAlarmExistUseCase.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/main/MainActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/main/home/HomeViewModel.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/ui/main/home/HomeComponent.kt
> #127 알람이 존재하는지 확인

- data/src/main/java/com/mashup/chinchin/data/datasource/remote/RemoteQuestionnaireDataSource.kt
- data/src/main/java/com/mashup/chinchin/data/dto/remote/responsebody/GetQuestionnaireResponse.kt
- data/src/main/java/com/mashup/chinchin/data/repository/QuestionnaireRepositoryImpl.kt
- data/src/main/java/com/mashup/chinchin/data/service/ChinChinService.kt
- domain/src/main/java/com/mashup/chinchin/domain/model/ReplyQuestionnaire.kt
- domain/src/main/java/com/mashup/chinchin/domain/repository/QuestionnaireRepository.kt
- domain/src/main/java/com/mashup/chinchin/domain/usecase/GetQuestionnareUseCase.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/reply_preference/ReplyPreferenceActivity.kt
- presenter/src/main/java/com/mashup/chinchin/presenter/reply_preference/ReplyPreferenceViewModel.kt
취향질문 답변 api response 값에 memberName 추가 대응
> 취향질문 답변 api response 값에 memberName 추가 대응
